#!/bin/bash
# Test script for document-processor interface
# Generated by plugin-validator

set -e

PLUGIN_BINARY="$1"
if [ -z "$PLUGIN_BINARY" ]; then
  echo "Usage: $0 <plugin_binary>"
  exit 1
fi

echo " Testing plugin: $PLUGIN_BINARY"
echo " Interface: document-processor"

echo "Testing manifest command..."
"$PLUGIN_BINARY" manifest > /tmp/manifest.json
echo "OK manifest command passed"

echo "Testing cap: extract-metadata..."
"$PLUGIN_BINARY" extract-metadata --help >/dev/null 2>&1 || true
echo "OK extract-metadata cap flag recognized"

echo "Testing cap: extract-outline..."
"$PLUGIN_BINARY" extract-outline --help >/dev/null 2>&1 || true
echo "OK extract-outline cap flag recognized"

echo "Testing cap: generate-thumbnail..."
"$PLUGIN_BINARY" generate-thumbnail --help >/dev/null 2>&1 || true
echo "OK generate-thumbnail cap flag recognized"

echo "Testing cap: grind..."
"$PLUGIN_BINARY" grind --help >/dev/null 2>&1 || true
echo "OK grind cap flag recognized"

echo "Testing cap: validate-file..."
"$PLUGIN_BINARY" validate-file --help >/dev/null 2>&1 || true
echo "OK validate-file cap flag recognized"

echo " All tests passed!"
