#!/bin/bash
# Test script for document-processor interface
# Generated by cartridge-validator

set -e

CARTRIDGE_BINARY="$1"
if [ -z "$CARTRIDGE_BINARY" ]; then
  echo "Usage: $0 <cartridge_binary>"
  exit 1
fi

echo " Testing cartridge: $CARTRIDGE_BINARY"
echo " Interface: document-processor"

echo "Testing manifest command..."
"$CARTRIDGE_BINARY" manifest > /tmp/manifest.json
echo "OK manifest command passed"

echo "Testing cap: extract-metadata..."
"$CARTRIDGE_BINARY" extract-metadata --help >/dev/null 2>&1 || true
echo "OK extract-metadata cap flag recognized"

echo "Testing cap: extract-outline..."
"$CARTRIDGE_BINARY" extract-outline --help >/dev/null 2>&1 || true
echo "OK extract-outline cap flag recognized"

echo "Testing cap: generate-thumbnail..."
"$CARTRIDGE_BINARY" generate-thumbnail --help >/dev/null 2>&1 || true
echo "OK generate-thumbnail cap flag recognized"

echo "Testing cap: grind..."
"$CARTRIDGE_BINARY" grind --help >/dev/null 2>&1 || true
echo "OK grind cap flag recognized"

echo "Testing cap: validate-file..."
"$CARTRIDGE_BINARY" validate-file --help >/dev/null 2>&1 || true
echo "OK validate-file cap flag recognized"

echo " All tests passed!"
